Задача 7. Добавить функционал по эпикам
druzhininyury/yandex-workshop-task-service pull request #6
Opened 2024-11-25 20:23 UTC by Hyacintholuscus

Изменены тесты по task в postman и в коде - устранены зависимости от конкретных id

2024-11-27 11:14 UTC, KurakinPavel commented
Очень хорошая работа, но есть на что обратить внимание.

При выкладке микросервисов на сервер в соответствии с задачами следующих спринтов у нас должна будет запускаться прилагаемая к коду коллекция тестов postman. Причём запускаться она будет через newman - инструмент, который позволяет запускать коллекции Postman непосредственно из командной строки компьютера.
При проверке запуска прилагаемой к пулл-реквесту коллекции postman через newman выяснилось, что ряд тестов не проходят. При это, при запуске через сам postman после импорта коллекции - проходят все тесты.
Возможно, после экспорта как-то некорректно работают переменные окружения.

2024-11-27 11:45 UTC, KurakinPavel requested changes

2024-11-27 11:45 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/taskservice/epic/dto/EpicDto.java
> +@Value
Мне ревьюер не рекомендовал использовать такие аннотацию, как @Data (а @Value на неё очень похожа).
Мнение и объяснение прилагаю.
<img width="828" alt="про аннотацию Data 1" src="https://github.com/user-attachments/assets/29bc8320-b05f-4534-8d41-71aa34ecb3ca">

2024-11-27 11:45 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/taskservice/epic/dto/NewEpicDto.java
> +@Value
Выше написал про сомнения по поводу аннотации @Value.

2024-11-27 11:45 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/taskservice/epic/service/EpicServiceImpl.java
> +                    .toList();
Сформировать список не найденных задач можно без нескольких итерации по спискам (что затратно по ресурсам, когда списки большие), а за счёт использования операций над множествами:

            Set<Long> gotTaskIds = new HashSet<>(tasks.stream().map(Task::getId).toList());
            taskIds.removeAll(gotTaskIds);
            List<Long> notFoundTasks = new ArrayList<>(taskIds);

2024-11-27 11:45 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/taskservice/epic/service/EpicServiceImpl.java
> +        }
Лучше формировать такой список единичным запросом к базе данных, так как в этом случае суммарные ресурсы (приложение + БД) будут использоваться эффективнее. Для этого предлагаю добавить в TaskRepository код:

    @Query("SELECT DISTINCT t.id FROM Task AS t WHERE t.eventId <> :eventId AND t IN :tasks")
    List<Long> findEpicIds(@Param("eventId") Long eventId,
                           @Param("tasks") List<Task> tasks);

В EpicServiceImpl, соответственно, будет запрос к TaskRepository:

        List<Long> otherEventTasks = taskRepository.findEpicIds(eventId, tasks);

2024-11-27 13:12 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/taskservice/epic/dto/UpdateEpicDto.java
> +@Value
Аналогично сказанному про @Value выше.

2024-11-28 11:26 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/taskservice/epic/service/EpicServiceImpl.java
> +        }
А вот так не сработает метод в репозитории?
`List<Long> findDistinctByEventIdNotAndIdIn(Long eventId, List<Long> taskIds);`

2024-11-28 11:34 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/taskservice/epic/dto/EpicDto.java
> +@Value
Павел, ты путаешь `@Data` для Dto и для Entity. Для entity автогенерация `@EqualsAndHash` будет конфликтовать с Hibernate, т.к. он на самом деле использует не наши классы, а надстройки над ними (что называется прокси-классами). И там возникают всякие опасные вещи, вроде ленивой загрузки. Для Dto `equals` и `hashCode` работают всегда корректно.

2024-11-28 12:30 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/taskservice/epic/dto/EpicDto.java
> +@Value
На момент написания ревьюером этого замечания Booking ещё не стало entity, так что замечание писалось ревьюером в целом по использованию @Data.
Кстати, посмотрел ещё информацию в сети по этому поводу - встречаются рекомендации вообще не использовать Lombok (ничего особого не делает), чтобы избежать в дальнейшем мучений с зависимостями при развитии проекта.

Но у нас, конечно, учебный проект, который вряд ли будет "жить" после его завершения.

2024-11-28 12:34 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/taskservice/epic/service/EpicServiceImpl.java
> +        }
Возможно, сработает, но предварительно всё равно придётся итерировать по списку, чтобы вытащить id тасков, от чего я и предлагаю уйти.

2024-11-28 12:37 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/taskservice/epic/dto/EpicDto.java
> +@Value
А какие именно проблемы Lombok привносит? Он же тупой кодогенератор. Без него мы либо будем делать тоже самое, либо использовать кодогенерацию, встроенную Idea?

2024-11-28 12:38 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/taskservice/epic/dto/EpicDto.java
> +@Value
В языке Kotlin некоторые элементы, схожие с  функциональностью Lombok, просто встроены в синтаксис языка.

2024-11-28 12:46 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/taskservice/epic/service/EpicServiceImpl.java
> +        }
Так разве твой вариант разве не развернется компилятором в аналог моего? Какой будет чистый SQL SELECT?

2024-11-28 14:05 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/taskservice/epic/service/EpicServiceImpl.java
> +        }
Hibernate: select distinct t1_0.task_id from public.tasks t1_0 where t1_0.event_id<>? and t1_0.task_id in (?,?)

Самое главное, что база данных выполнит такой запрос с помощью Prepared Statement, что эффективнее, чем делать это в коде Java.

2024-11-28 14:15 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/taskservice/epic/dto/EpicDto.java
> +@Value
Основная претензия в том, что версия библиотеки может конфликтовать со средой развёртывания проекта. 
И если она ничего особо важного не делает (а сгенерировать то, что делает Lombok, можно нажатием пары кнопок в любой IDE), то и юзать её не стоит.

2024-11-29 05:42 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/taskservice/epic/dto/EpicDto.java
> +@Value
Я соглашусь с первым комментарием Юрия по поводу Data и Value. Так как комментарий был дан ещё до становления модели Entity, скорее всего это был совет на будущее, связанный с проблемами Hibernate и автоматической генерацией кода от Lombok. Так что на DTO использовать эти аннотации, как я считаю - нормальная практика, т. к. здесь генерация всех методов будет корректной.
Если принципиально поменять на другие аннотации, я могу, но разницы в этом особой не будет, ведь по сути своей аннотация Data или Value - это просто использование тех же аннотаций, которые есть в FullTaskDto, например, только вместо нескольких разных аннотаций используешь одну.

2024-11-29 05:56 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/taskservice/epic/service/EpicServiceImpl.java
> +        }
С одной стороны выглядит, вроде, хорошо, но, получается тут будет ещё один вызов БД, которого можно было бы избежать. Может, тогда просто сделать поиск задач сразу и по id самих задач и по eventId, а потом кидать notFound, что задач с id таким-то, относящимся к eventId такому-то не найдено. Ну, или конфликт. Насчёт исключения не знаю, какое лучше здесь подойдёт

2024-11-29 05:59 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/taskservice/epic/service/EpicServiceImpl.java
> +                    .toList();
Спасибо)

2024-11-29 07:22 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/taskservice/epic/dto/EpicDto.java
> +@Value
Скорее, это предложение обратить внимание на возможные сложности с аннотациями и вообще применением Lombok в дальнейшем. В текущий проект библиотека слишком сильно интегрирована, чтобы от неё отказываться и переделывать код.

2024-11-29 07:22 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/taskservice/epic/dto/NewEpicDto.java
> +@Value
Выше написал.

2024-11-29 07:25 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/taskservice/epic/dto/UpdateEpicDto.java
> +@Value
Отметил, что для учёта на будущее.

2024-11-29 07:43 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/taskservice/epic/service/EpicServiceImpl.java
> +        }
В единичном вызове БД для проверки чего-либо нет ничего страшного, особенно, если оптимизировать сам запрос. БД и её окружение для этого и созданы. А вот итераций по коллекции лучше избегать, так как это всегда "затратная" операция. 

Искать сразу с учётом eventId - можно. Но это:
- сократит для пользователя удобство пользования приложением (сложнее разобраться, что не так со списком предлагаемых для внесения в эпик задач);
- потребует переделки тестов, чего я никому не пожелаю.

При запуске из Postman прилагаемая коллекция с предлагаемыми правками полностью отрабатывает, проверял. Через newman - часть тестов слетает.

2024-11-29 07:54 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/taskservice/epic/service/EpicServiceImpl.java
> +        }
> (?,?)

А вот сюда, что подставляется? Подозреваю, что именно id, который вычисляются hibernate на стороне приложения.

2024-11-29 08:07 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/taskservice/epic/service/EpicServiceImpl.java
> +        }
Да, только hibernate делает это значительно эффективнее, чем использование циклов в коде.

2024-11-29 11:21 UTC, KurakinPavel approved these changes

2024-11-30 08:36 UTC, merged